# Determine how many barcodes of each library variant are present in a library
# input :read the .unq file for a RNA-MaP library generated by compressBarcodes_v8.py (greenleaf lab program)
#loop through the consensus seq column and make a dictionary counter for each time this matches one of the 30,000 seqs ordered
#output: a histogram of all 29,800 seqs ordered from CustomArray witht he number of barcode hits
# make a csv with the dictionary consensus seqs and the number of counts they had

# make a list of all input seqs
# make a matching list of counters (by position)

import pandas as pd
import sys

#tool to troubleshoot if needed:

# rvs_comp function takes a list of sequences and outputs an equal length list of the rvs_complements of the sequences it read

libcharfilename = sys.argv[1]
bcseqfilename = sys.argv[2]
outputfilename = sys.argv[3]


lc = pd.read_csv(libcharfilename)
libchar = lc.loc[:, ['rcseq', 'variant', 'chip_sequence']]
print "Initial list of designed variants : ", libchar.shape[0]
libchar = libchar.drop_duplicates(subset = ['chip_sequence'])
print "Reduced unique list of designed variants : ", libchar.shape[0]
consen = pd.read_csv(bcseqfilename, sep="\t")
consen = consen.loc[:, ['sequence', 'barcode']]

ncon = consen.shape[0]
nlib = libchar.shape[0]

barcodes = []
assigned_variants = []

cassign = []
lassign = [] 
seqassign = []

lrcs = []


print "running comparison"
for i in range(ncon):
    print i
    for j in range(nlib):
        c = consen.iloc[i]
	l = libchar.iloc[j]
	if l['rcseq'] in c['sequence']:
	    cassign.append(c['barcode'])
	    lassign.append(l['variant'])
	    seqassign.append(l['chip_sequence'])

out = pd.DataFrame()
out['barcode'] = cassign
out['variant'] = lassign
out['sequence'] = seqassign
out.to_csv(outputfilename, sep="\t", header=True, index=False)
